config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :lists do
    resources :todos, only: [:new, :create, :show] do
      member do
        post :complete
      end
    end
  end

  root to: 'lists#index'
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user

  has_many :todos, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true, uniqueness: { scope: :user }
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :list

  validates :list, presence: true
  validates :description, presence: true, uniqueness: { scope: :list }

  def complete?
    completed_at.present?
  end

  def complete!
    update completed_at: Time.now
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists, dependent: :destroy
  has_many :todos, through: :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = current_user.lists.all
  end

  def show
  end

  def new
    @list = current_user.lists.new
  end

  def edit
  end

  def create
    @list = current_user.lists.new list_params
    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  def update
    if @list.update list_params
      redirect_to @list, notice: 'List was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, notice: 'List was successfully destroyed.'
  end

private

  def set_list
    @list = current_user.lists.find params[:id]
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_list

  def new
    @todo = @list.todos.new
  end

  def create
    @todo = @list.todos.new todo_params
    if @todo.save
      redirect_to @list, notice: 'Todo created'
    else
      render :new
    end
  end

  def show
    @todo = @list.todos.find params[:id]
  end

  def complete
    @message = ["Got it!", "Nice work!", "Keep it up!", "Attaboy!"].sample
    @todo = @list.todos.find params[:id]
    @todo.complete!
    #redirect_to @list, notice: 'Todo completed'
  end

private

  def set_list
    @list = current_user.lists.find params[:list_id]
  end

  def todo_params
    params.require(:todo).permit(:description, :due_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class name
    # Translate rails conventions to bootstrap conventions
    case name.to_sym
    when :notice
      :success
    when :alert
      :danger
    else
      name
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoRails</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="flash">
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= flash_class name %>" >
          <%= msg %>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <%= render partial: 'partials/errors', locals: { object: @list } %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Lists</h1>
<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.title, list %></li>
  <% end %>
</ul>

<%= link_to 'New List', new_list_path, class: "btn btn-success" %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<h1>
  <%= @list.title %>
</h1>

<div class="btn-group">
  <%= link_to 'Back', lists_path, class: "btn btn-default" %>
  <%= link_to 'Edit', edit_list_path(@list), class: "btn btn-default" %>
  <%= link_to 'Delete', list_path(@list), method: "delete", class: "btn btn-default", data: { confirm: "Are you sure?" } %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Description</th>
      <th>Due</th>
      <th>Complete</th>
    </tr>
  </thead>
  <tbody>
    <% @list.todos.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td>
          <% if item.due_on %>
            <%= item.due_on %> (<%= distance_of_time_in_words item.due_on, Time.now %> from now)
          <% end %>
        </td>
        <td>
          <% if item.complete? %>
            <%= item.completed_at %>
          <% else %>
            <%= form_tag complete_list_todo_path(@list, item) do %>
              <button class="btn btn-danger mark-complete" data-todo-id="<%= item.id %>" data-list-id="<%= @list.id %>">Mark Complete</button>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Item", new_list_todo_path(@list), class: "btn btn-success" %>

app/views/partials/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name.downcase %> from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/todos/new.html.erb
<h1>New Todo for '<%= @list.title %>'</h1>

<%= form_for [@list, @todo] do |f| %>
  <%= render partial: 'partials/errors', locals: { object: @todo } %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :due_on %>
    <%= f.date_field :due_on, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Back', list_path(@list) %>

app/views/todos/show.html.erb
<p>This is the show page for <%= @todo.description %></p>